language: go

# we use :443 in tests
sudo: required

go:
  - 1.8
  - 1.8.x
  - 1.9rc1
  - 1.9rc2
  - 1.9
  - 1.9.1
  - 1.9.2
  - 1.9.x
  - tip

cache:
  directories:
    - $HOME/.longtestcache
  timeout: 21600

allow_failures:
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
