language: go

# we use :443 in tests
sudo: required

go:
  - 1.7
  - 1.8
  - stable
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)